from .appearance import APPEARANCE_SHIFT_PRESETS, get_appearance_shift_spec, get_image_shift, get_scene_properties
from .deployment import (
    PreservingDeploymentResult,
    deploy_default_action,
    deploy_full_action,
    deploy_preserving_action,
)
from .fusion import fuse_full_action, fuse_preserving_action, weak_fuse_actions
from .gate import (
    PreservingGateConfig,
    PreservingGateInputs,
    PreservingGateScores,
    compute_action_gate,
    compute_phase_gate,
    compute_preserving_gate,
    compute_semantic_gate,
    compute_visual_gate,
)
from .probe import (
    PreservingProbeOutput,
    StyleProbeConfig,
    StyleTriggerConfig,
    build_style_probe_output,
    build_style_probe_view,
    compute_style_probe_diagnostics,
    compute_style_probe_statistics,
)
from .grounded_probe import (
    GroundedProbeConfig,
    GroundedProbeOutput,
    GroundingBackend,
    GroundingBox,
    GroundingResult,
    MaskRefinementResult,
    SegmentationBackend,
    apply_mask_overlay,
    attenuate_background,
    build_grounded_probe_output,
    build_grounding_queries,
    merge_foreground_masks,
)
from .backends import (
    GroundedBackendBundle,
    TransformersGroundedBackendConfig,
    TransformersGroundingDinoBackend,
    TransformersSam2Backend,
    UnavailableGroundingBackend,
    UnavailableSegmentationBackend,
    build_grounded_backend_bundle_from_env,
    build_transformers_backend_bundle,
    build_unavailable_backend_bundle,
)
from .selector import PreservingProbeSelectorConfig, select_preserving_probe_output
from .pipeline import (
    PreservingPipelineConfig,
    PreservingPipelineInputs,
    PreservingPipelineResult,
    run_preserving_pipeline,
)

__all__ = [
    "APPEARANCE_SHIFT_PRESETS",
    "GroundedBackendBundle",
    "TransformersGroundedBackendConfig",
    "TransformersGroundingDinoBackend",
    "TransformersSam2Backend",
    "GroundedProbeConfig",
    "GroundedProbeOutput",
    "GroundingBackend",
    "GroundingBox",
    "GroundingResult",
    "MaskRefinementResult",
    "PreservingDeploymentResult",
    "PreservingGateConfig",
    "PreservingGateInputs",
    "PreservingGateScores",
    "PreservingProbeOutput",
    "PreservingProbeSelectorConfig",
    "PreservingPipelineConfig",
    "PreservingPipelineInputs",
    "PreservingPipelineResult",
    "SegmentationBackend",
    "apply_mask_overlay",
    "attenuate_background",
    "build_grounded_probe_output",
    "build_grounding_queries",
    "build_grounded_backend_bundle_from_env",
    "build_transformers_backend_bundle",
    "build_unavailable_backend_bundle",
    "StyleProbeConfig",
    "StyleTriggerConfig",
    "UnavailableGroundingBackend",
    "UnavailableSegmentationBackend",
    "build_style_probe_output",
    "build_style_probe_view",
    "compute_action_gate",
    "compute_phase_gate",
    "compute_preserving_gate",
    "compute_semantic_gate",
    "compute_style_probe_diagnostics",
    "compute_style_probe_statistics",
    "compute_visual_gate",
    "deploy_default_action",
    "deploy_full_action",
    "deploy_preserving_action",
    "fuse_full_action",
    "fuse_preserving_action",
    "get_appearance_shift_spec",
    "get_image_shift",
    "get_scene_properties",
    "merge_foreground_masks",
    "run_preserving_pipeline",
    "select_preserving_probe_output",
    "weak_fuse_actions",
]
